#190/show required fields lables on add item page by default
enBloc-org/kindly pull request #213
Opened 2024-05-20 19:09 UTC by AlexVOiceover

# Description

** Closes #190**  
The add item form now shows correctly the fields that need to be filled even when an image wasn't attached yet. The previous behaviour was forcing the user to have an image uploaded.

### Files changed

app/(dashboard)/add-item/page.tsx
Makes the comprobation of the image being uploaded

components/form/UploadImageInput.tsx
Will pass as a prop a flag to specify if the image was uploaded (onImageUpload)

app/(dashboard)/add-item/pageTypes.ts
This file was created to extend the type PartialItem to include the boolean 'imageUploaded'

### UI changes

![image](https://github.com/enBloc-org/kindly/assets/94972293/ac390878-7cf2-4bdf-b828-fd44b3d26e52)

# Tests

 Manual tested. Try to create item without image and without some required fields

2024-05-22 15:14 UTC, eliazzo commented on .eslintrc.json
> +  "settings": {
Is this file change intentional? If so, what is this doing

2024-05-22 15:43 UTC, eliazzo commented on app/(dashboard)/add-item/page.tsx
> +    setValue('imageUploaded', isUploaded); // Update and validate the field
remove this comment :)

2024-05-22 15:47 UTC, eliazzo commented on components/form/UploadImageInput.tsx
> +      {/*!isImageUploaded && (
remove comments

2024-05-22 15:47 UTC, eliazzo commented on components/form/UploadImageInput.tsx
> +        //setIsImageUploaded(true);
remove comments/ unused code

2024-05-22 15:48 UTC, camelPhonso commented on app/(dashboard)/add-item/page.tsx
> +  console.log(isPostageCovered, setValue, isImageUploaded);
🧹 console logs need to be removed

2024-05-22 15:50 UTC, eliazzo commented on app/(dashboard)/add-item/page.tsx
> +  console.log(isPostageCovered, setValue, isImageUploaded);
remove logs

2024-05-22 15:51 UTC, eliazzo commented on components/form/UploadImageInput.tsx
> +  onImageUpload: (isUploaded: boolean) => void;
should this just be the setter for a new state?

2024-05-22 15:52 UTC, camelPhonso commented on app/(dashboard)/add-item/pageTypes.ts
> +//This type extends PartialItem with the boolean imaheUploaded
![Uploading ghostbusters.gif…]()

2024-05-22 15:52 UTC, eliazzo commented on components/form/UploadImageInput.tsx
> +  // const [isImageUploaded, setIsImageUploaded] = useState(false);
remove comments/ unused code

2024-05-22 16:57 UTC, camelPhonso commented on app/(dashboard)/add-item/pageTypes.ts
> +//This type extends PartialItem with the boolean imaheUploaded
That was supposed to show the ghostbusters - to tell you to delete comments 👻

2024-05-24 09:44 UTC, eliazzo commented on app/(dashboard)/add-item/page.tsx
> +    setValue('imageUploaded', isUploaded); // Update and validate the field
```suggestion
    setValue('imageUploaded', isUploaded); 
```
remove comment

2024-07-05 10:15 UTC, camelPhonso commented on .eslintrc.json
> +  },
```suggestion

```

2024-07-05 10:35 UTC, camelPhonso commented on .gitignore
> +.DS_StoreThe
```suggestion
.DS_Store
```

2024-07-05 10:37 UTC, nichgalzin approved these changes

2024-07-05 10:40 UTC, nichgalzin commented
Hey @AlexVOiceover, 
    Can you please resolve the issues on on PR with the example .env file. Please and thanks. Then we can merge this PR.

2024-07-07 11:27 UTC, AlexVOiceover commented
Hi @nichgalzin and team,

I have resolved the conflicts by merging the latest changes from the `dev` branch into my feature branch and deleting the `.env.example` file as per the upstream changes. The PR should now be ready for merging.

Thank you!

2024-08-16 09:42 UTC, camelPhonso requested changes
Thanks for the update Alex.

Asked to remove an unnecessary file here.

2024-08-16 09:42 UTC, camelPhonso commented on playwright-report/index.html
We no longer use Playwright on the code base so I presume this is an old report that got staged. Can you remove this from the PR please?

2024-08-26 20:54 UTC, AlexVOiceover commented
The comprobation of the mandatory fields on the form and the presence of the image cannot be done in separate react components, that way it will only perform the "outer" component once that the nested one was resolved.
All comprobations were moved to the parent (AddNewItemForm.tsx).
For a similar reason it was needed to add the function handleFormSubmit as some kind of middleware. It will update isSubmitAttempted before trying to submit, so all the form mandatory fields comprobations and the error messages for the checkboxes and the image will be done at once.
Without this function,  submitHandler will check the mandatory fields, and only after everything is right will carry on with checking the image.

setError and isRequired were left on the props for compatibility with other potential components that use this functionality, these should be udpated.

2024-09-12 10:43 UTC, camelPhonso commented
Closing this PR as the issue has been handed over to another contributor

2024-09-12 10:43 UTC, closed without merging