#260/feat: Allow Users to mark their Items as 'Given Away'
enBloc-org/kindly pull request #337
Opened 2024-09-17 18:17 UTC by YuraPetrovskyi

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review on my code
- [ ] I have made corresponding changes to the documentation (if any were needed)
- [ ] My changes generate no new warnings or errors
- [ ] Any dependent changes have been merged and published in downstream modules

# Description

Relates #260 #254   
- Implemented feature to allow users to mark their items as "Given Away"
- Added GiveAwayConfirmationModal component to confirm the donation process
- Updated item status and messaging logic to notify the user when an item is given away
- Added filtering to exclude items marked as "Given Away" from search results

### Files changed

#### DonatedItemsList.tsx
- Integrated the new GiveAwayConfirmationModal.
- Adjusted the logic for marking an item as "Given Away" and added notifications for the item recipient.

#### GiveAwayConfirmationModal.tsx (New)
- Created a modal for confirming item donation, ensuring the user is informed about the action before marking the item as given away.

#### ItemCard.tsx
- Added logic to display labels like "RESERVED" and "GIVEN AWAY" based on item status.

#### ItemDetailsPage.tsx
- Added notification logic for item reservation, ensuring system messages are sent when an item is requested to be reserved.

#### ReserveForUserModal.tsx
- Adjusted reserve status handling, ensuring the item's reservation status and the user ID are properly updated and managed.

#### supabase/migrations/20240913135301_add_given_away_to_column.sql (New)
-Added migration to include given_away_to column in the items table to track the user receiving the donated item.

#### supabase/models/filtering-items/searchItems.ts
- Updated filtering logic to exclude items marked as given away, ensuring only available items are shown.

#### supabase/models/messaging/findConversationByItemAndUsers.ts (New)
- Added a function to find an existing conversation between a user and the reserved recipient related to a specific item.

#### types/supabaseTypes.ts
- Updated the types to include the given_away_to field for tracking the recipient of donated items.

# Tests

All tests have been conducted manually, and no errors have been identified.

2024-09-20 06:53 UTC, camelPhonso commented
Hi @YuraPetrovskyi could you run `npx cypress open` on your branch and check what's causing a fail in one of our authorisation tests? The workflow is flagging it

![Screenshot 2024-09-20 at 07 52 04](https://github.com/user-attachments/assets/8a259e01-b79a-4a92-939b-bf9765a704e0)

2024-09-20 09:45 UTC, camelPhonso commented
closes #260

2024-09-20 15:45 UTC, YuraPetrovskyi commented
Hi @camelPhonso  . I fail the new user authorization test. Incidentally, I cannot register a new user, and I use previously created users. When trying to create a new user, I do not receive a confirmation email. A user is created in the database, but it is impossible to log in later under this name. Not sure if my code changes have any effect on this. I must say that I made some corrections in supabaseTypes.ts ( I changed id: String to id: string, email: String to email: string ), but I checked where they are used and I think my changes do not change the logic of the program. What should my next steps be, what do you recommend?
I can roll back the changes regarding supabaseTypes.ts and make the appropriate changes in my code, what do you say? (I have already tried different options, it does not affect authorization)

2024-09-23 08:44 UTC, camelPhonso commented
> Hi @camelPhonso . I fail the new user authorization test. Incidentally, I cannot register a new user, and I use previously created users. When trying to create a new user, I do not receive a confirmation email. A user is created in the database, but it is impossible to log in later under this name. Not sure if my code changes have any effect on this. I must say that I made some corrections in supabaseTypes.ts ( I changed id: String to id: string, email: String to email: string ), but I checked where they are used and I think my changes do not change the logic of the program. What should my next steps be, what do you recommend? I can roll back the changes regarding supabaseTypes.ts and make the appropriate changes in my code, what do you say? (I have already tried different options, it does not affect authorization)

I remember there being a discussion on the discord about 'String' vs 'string' in one of our types that was causing some trouble. In any case, unless there's a specific reason why we think it's better to refactor this I wouldn't be changing the types anyway so it's worth reverting those and running tests again. If they still fail maybe share the error message you get so we can figure out what's causing it

2024-09-27 11:20 UTC, camelPhonso requested changes
I made some notes on potentially simplifying code but your implementation is looking great Yura!! top stuff 👌 

We should also add tests however. Probably the best thing would be to reset the database, then mark on of your items as reserved and do a data dump to update the seed data and then to create a test that checks the flow of clicking `give away` on the item

2024-09-28 18:17 UTC, camelPhonso commented on components/DonatedItemsList.tsx
> +            'This item has been marked as Given Away and is no longer available.'
woop, please disregard this one comment, I thought I had deleted it before posting the review - it was my container acting up and I just needed to restart that

2024-09-30 09:02 UTC, YuraPetrovskyi commented on components/DonatedItemsList.tsx
> +          : item
"Thank you for the suggestion! I agree that making reservedBy optional and setting it to "" by default could make the function more flexible. I'll go ahead and implement this change."

2024-09-30 11:26 UTC, YuraPetrovskyi commented on components/ItemCard.tsx
> +        ) : null}
Thank you @camelPhonso ! This will certainly be done!

2024-09-30 15:52 UTC, YuraPetrovskyi commented on components/GiveAwayConfirmationModal.tsx
From the very beginning, I wanted to use this Modal, but since it was adapted to the delete function, I thought of creating a similar new one. I have already redesigned this module to be universal. Accordingly, it was necessary to make some changes in other components. Look what I got),  now it is necessary to make changes in the Story Book and in the tests 🤯

2024-09-30 17:10 UTC, YuraPetrovskyi commented
Hi @camelPhonso , it seems I'm done with the main work) and have completed all your comments except for the test. Could you please clarify what I need to do for the test? Whether to create a new test in cypress or to make changes to some existing one, since I do not know deeply about these thing🤪🤦‍♂️🤷‍♀️🙏

2024-09-30 19:18 UTC, YuraPetrovskyi commented
Locally, the test works for me, but previously I created the 'give_away' item and made the reservation, and then the test "went like clockwork" )

2024-10-04 15:16 UTC, camelPhonso commented on components/GiveAwayConfirmationModal.tsx
hahaha, these are the pains of a well documented/tested project 😅

2024-10-04 15:41 UTC, camelPhonso commented
> Hi @camelPhonso , it seems I'm done with the main work) and have completed all your comments except for the test. Could you please clarify what I need to do for the test? Whether to create a new test in cypress or to make changes to some existing one, since I do not know deeply about these thing🤪🤦‍♂️🤷‍♀️🙏

ok so it seems like your test is running into issues because it assumes the shoes have been marked as reserved, but when we start with the seed data that's not the case.

The shoes are used in the `resrved.cy.js` suite so we should leave those as they are but the best thing to do would be to have one of the other items reserved and then run the test to give away on that one.

To do this, the best way is to do these steps:

- `npx supabase db reset` to start with clean data again
- log in as the refugee and request an item - maybe the summer dress
- log in as the donor and mark as reserved
- do a [data dump](https://supabase.com/docs/reference/cli/supabase-db-dump) to update our seed data
- then adjust your test to target the summer dress and mark it as given away

2024-10-07 14:11 UTC, YuraPetrovskyi commented
> To do this, the best way is to follow these steps:
> 
> * `npx supabase db reset` to start with clean data again
> * log in as the refugee and request an item - maybe the summer dress
> * log in as the donor and mark the summer dress as reserved
> * do a [data dump](https://supabase.com/docs/reference/cli/supabase-db-dump) to update our seed data
> * then adjust your test to target the summer dress and mark it as given away

Thanks @camelPhonso  for the advice👍 now everything is working 🥳

2024-10-13 19:35 UTC, OlenaReukova commented
@YuraPetrovskyi ,  Looks great 👍The test ran successfully, and the giveaway functionality worked as expected.

2024-10-14 07:33 UTC, merged

2024-10-14 11:27 UTC, YuraPetrovskyi commented
> Another smashing contribution 🙌 Thanks Yurii

I am very happy🥳🤩 Thanks @camelPhonso for the tips and for the right direction💪it was great to work on this assignment👍