#340: Sizes update
enBloc-org/kindly pull request #347
Opened 2024-09-23 20:37 UTC by AnyaVeselova

# Description

**Relates #340 **  
This pull request:
- isolates sizes array initialization and sizes selection logic into a separate component for cleaner code, better separation of concerns, and easier updates or adjustments later
- adds more sizes option (including half shoe sizes)
- creates a new euShoeSizes array
- imports the component inside the form of a parent component

### Files changed

 - SizeSelector.tsx has been created
 - AddNewItemForm.tsx

2024-09-27 14:06 UTC, ShaughnAnderson94 requested changes

2024-09-27 14:06 UTC, ShaughnAnderson94 commented on components/messaging/ConversationCard.tsx
the shoe gird is looking good however this code relating to conversation card probably shouldn't be in this issue (be careful of the stuff we talked about earlier and just do a git status every now and then to see what you are committing/check your new branch is new)

2024-10-11 11:12 UTC, nichgalzin requested changes
Thanks a lot for this Anya! Left a few requests for changes. Let me know if you have any questions!

2024-10-11 11:12 UTC, nichgalzin commented on components/form/SizeSelector.tsx
> +  let sizeOptions: string[] = [];
I think the refactor of this logic to it's own component is great I really like the cleaning up of the AddNewItemForm component to be doing less. However the use of ```let``` here, while totally functional and probably fine for a simple case like this is probably better put into a local state variable using the react useState hook.

2024-10-11 11:12 UTC, nichgalzin commented on components/form/SizeSelector.tsx
> +  if (category === 'clothing') {
Keeping in line then with the above logic you would then wrap this logic in the useEffect hook and put the category prop in the dependency array. Again what you did here is totally fine from a logic point of view, but this implementation will fit a bit better the React conventions we're using in the rest of the project.

2024-10-14 10:26 UTC, nichgalzin requested changes
Hi Anna,
   This is all looking great. Can you please just remove the middleware.ts file from the this pr and then I can approve it? This looks just like an auto formatting thing and the code has been repeated. In any case this is unrelated to this PR and we want to avoid unintentional code changes to unrelated file. Thanks for this, fix this and we can merge this PR!

2024-10-18 22:04 UTC, closed without merging