#77/date markers
enBloc-org/kindly pull request #82
Opened 2024-02-26 18:22 UTC by camelPhonso

Added markers for each new day that are only visible if the user is scrolling through messages - pretty much emulated the behaviour of any major messaging app out there.

This div is only rendered whenever the date of the message is a different day from the previous message - this is done with an evaluation in the .map method using the index value which we are now calling there.

![Screenshot 2024-02-26 at 18 11 48](https://github.com/enBloc-org/kindly/assets/114600712/fa40b586-6b13-4866-a87d-72e0791c4430)

![Screenshot 2024-02-26 at 18 19 30](https://github.com/enBloc-org/kindly/assets/114600712/f3aa7b6f-819b-4b27-beaa-121be230270f)

Date Markers have the following behaviour:
- Will stay at the top when scrolling and replace one-another in sequence
- Will fade out after 3 seconds of the user no longer scrolling
- Will stay centred in any screen size
- Will always be juxtaposed over MessageCards

The following lines will have to be reviewed if we are changing the return value of the date on our database query, which I am happy to take on in a separate PR if no one is working on it right now, but I thought it best to keep it out of this request:

```js
 {message.created_at.slice(0, 10) !==  // we'll need to adjust this evaluation depending on what we are actually returning
              currentMessages[index - 1]?.created_at.slice(0, 10) && ( // for now I am doing the manipulation in-line
              <div
                className={`${isScrolling ? 'opacity-100' : 'opacity-0'} sticky top-4`}
              >
                {message.created_at.slice(0, 10)}
              </div>
            )}
```

@eliazzo - I have removed the `flex-col-reverse` while working on this to see the final result, but my understanding is that it was intended to help with keeping the messages scrolled to the bottom, which we are now tackling differently. So do we need the messages in reverse order for any other reason?

P.S.: Got to play around with debouncing which was really fun 🎪

2024-02-28 16:13 UTC, eliazzo commented
I think we do still need the ```flex-col-reverse```. We are going to reverse the order of the messages that are coming from supabase which will put the latest messages at the start of the array. The ```flex-col-reverse``` relates to how we view them (instead of displaying top to bottom we want to display bottom to top)

2024-02-29 12:29 UTC, camelPhonso commented
> These look great but they do not match the styling as per the figma? Dates should be written as follows `2 February` or `Today`. We opted for a grey text colour with no background. Screenshots were included in issue #77 for styling guidance

Restyled the date markers. They now have a background that matches the background of CurrentCoversation so they show the same as our figma but will display a background when scrolling over any messages.

![Screenshot 2024-02-29 at 12 14 29](https://github.com/enBloc-org/kindly/assets/114600712/80abd35c-7c6e-4a2d-8db6-9c3c0065d7ee)

![Screenshot 2024-02-29 at 12 15 08](https://github.com/enBloc-org/kindly/assets/114600712/53c3f01c-20d6-4e42-aa08-867b7e215179)

![Screenshot 2024-02-29 at 12 29 13](https://github.com/enBloc-org/kindly/assets/114600712/89d4c371-628d-4517-97bf-feaadf2f2d1d)

2024-02-29 12:30 UTC, camelPhonso commented
> I think we do still need the `flex-col-reverse`. We are going to reverse the order of the messages that are coming from supabase which will put the latest messages at the start of the array. The `flex-col-reverse` relates to how we view them (instead of displaying top to bottom we want to display bottom to top)

Added reverse back to the styling :)

2024-03-01 08:35 UTC, camelPhonso commented
Added helper functions to edit the timestamptz coming out of our database into the formats needed in our UI.

Two helper functions in the utils/messaging folder being exported from the file `formatTimeStamp.ts`:
- createDateMarker.ts
- createTimeMarker.ts

2024-03-01 09:39 UTC, nichgalzin requested changes
3 notes:
  
1). Do we think the util functions for follow the naming convention of the file they are in, which I think possibly describes their functionality better. So instead of createTimeMarker, it's formatTimerMaker and so on?

2). Not sure if this going to be an issue when the CurrentConversation is styled to the correct size which I'm doing in my current issue, but the Date marker goes over the mobile nav bar when you scroll. We might want to play with the z-index just in case.
<img width="724" alt="Screenshot 2024-03-01 at 09 30 46" src="https://github.com/enBloc-org/kindly/assets/74174344/5f1c772f-c36f-47ec-92a6-a105cb12f540">


3). I think the date stamp should be it's own component. I think this is too much logic in this parent component for this not to separated into it's own file. What do you think?
![Uploading Screenshot 2024-03-01 at 09.32.55.png…]()

2024-03-01 10:37 UTC, camelPhonso commented
> 1). Do we think the util functions for follow the naming convention of the file they are in, which I think possibly describes their functionality better. So instead of createTimeMarker, it's formatTimerMaker and so on?

Yes, that's probably clearer. I've renamed them to `formatDateMarker` and `formatTimeMarker` respectively.

> 2). Not sure if this going to be an issue when the CurrentConversation is styled to the correct size which I'm doing in my current issue, but the Date marker goes over the mobile nav bar when you scroll. We might want to play with the z-index just in case.

This is happening because the date marker has a higher Z-index in order to superimpose on the messages when we scroll, but because CurrentConversation at the moment scrolls on the page it leads this visual effect. Shouldn't be a problem once issue #73 is closed.

> 3). I think the date stamp should be it's own component. I think this is too much logic in this parent component for this not to separated into it's own file. What do you think?

I actually don't think that one would be very good practice. The component wouldn't really be reusable anywhere else in the code and it wouldn't save us from importing utils onto CurrentConversation or make the code shorter. 

We'd still need to make an evaluation there to display the date-marker conditionally and we'd only swap out the util callback inside a `div` for that component. So it saves maybe three lines by sacrificing on a cluttered file structure.

This:
```js
{currentMessages.map((message: MessageType, index: number) => (
          <div key={`${message.id}-${message.created_at}`}>
            {formatDateMarker(message.created_at) !==
              formatDateMarker(currentMessages[index - 1]?.created_at) && (
              <div
                className={`${isScrolling ? 'opacity-100' : 'opacity-100'} sticky top-4 z-10 my-[-15px] ml-[calc((100%_-_120px)/2)] h-[30px] w-[120px] rounded-xl bg-stone-50 object-center p-1 text-center text-lg font-semibold text-slate-400 transition transition-opacity ease-in-out`}
              >
                {formatDateMarker(message.created_at)}
              </div>
            )}
```

becomes this:
```js
{currentMessages.map((message: MessageType, index: number) => (
          <div key={`${message.id}-${message.created_at}`}>
            {formatDateMarker(message.created_at) !==
              formatDateMarker(currentMessages[index - 1]?.created_at) && (
              <DateMarker />
            )}
```

I'm not sure the swap is worth it 🤔 but I'm happy to make the refactor if others agree it's best

2024-03-01 15:17 UTC, nichgalzin approved these changes
After small changes in the conversation we had.
-Fixed the opacity ternary value
-removed redundant transition class

2024-03-01 15:22 UTC, merged